---
title: "Schinus_substrate_fertilizer"
author: "Jorge Alonso"
date: "2026-05-18"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: show
    self_contained: true
---

# 1. Preparing

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.width = 7,
  fig.height = 5,
  dpi = 300)
```

## 1.1. Loading packages and data

```{r, message = FALSE}
# Loading packages
library(openxlsx)
library(tidyverse)
library(bestNormalize)
library(ExpDes.pt)
library(cowplot)
library(ggcorrplot)
library(psych)
library(factoextra)  
```


```{r, message = FALSE}
# Cleaning memory
rm(list=ls(all=TRUE))
gc()
```


```{r}
# Database link
raw_url <- "https://raw.githubusercontent.com/jmalonso55/substrate_fertilier_schinus/refs/heads/main/stat_aroeira.csv"
```


```{r}
# Loading data
data <- read.csv(raw_url, sep = ",")

# Checking
summary(data)
```


## 1.2. Recoding variables

```{r}
# Treatments to factor
data <- data %>% 
  mutate(Trat = as.factor(Trat), Subst = as.factor(Subst), Rate_f = as.factor(Rate)) 

# Checking
str(data)
```


## 1.3. Establishing functions and plot themes

```{r}
# Function to check the assumptions and return the ANOVA
assumptions <- function(y, x, w) {
  mod <- aov(y ~ x * w)
  norm <- shapiro.test(mod$residuals)
  hom <- bartlett.test(y, interaction(x, w))
  print(norm)
  print(hom)
  
  if (norm$p.value > 0.05 && hom$p.value > 0.05) {
    cat("\nANOVA table (Assumptions met):\n")
    print(summary(mod))
  } else {
    cat("ANOVA was not performed because its assumptions were not met.\n")
  }
}
```


```{r}
# Generic theme for plots
tema <- theme(panel.background = element_rect(fill = "grey97"), 
        panel.grid.major.x = element_line(color = "grey85", linetype = "dotted"),
        panel.grid.major.y = element_line(color = "grey85", linetype = "dotted"),
        text = element_text(family = "serif", size = 12),
        axis.text = element_text(size = 11, color = "black"))
```


# 2. Experiment Analysis

## 2.1. Checking Assumptions

```{r}
for(i in 6:12) {
  resp <- data[[i]]
  cat("\n
      ANOVA for", names(data)[i], "\n")
  assumptions(resp, data$Subst, data$Rate_f)
}
```


## 2.2. Transforming variables and rechecking

### 2.2.1. Height 

```{r}
# Log transformation
with(data, assumptions(log(Height), Subst, Rate_f))
```

### 2.2.2. RDM

```{r}
# Log transformation
with(data, assumptions(log(RDM), Subst, Rate_f))
```

```{r}
# Checking best transformation
bestNormalize(data$RDM)
```


```{r}
# Boxcox transformation
RDM_t <- orderNorm(data$RDM)

# Checking assumptions
assumptions(RDM_t$x.t, data$Subst, data$Rate_f)
```


## 2.3. Means comparison with interactions for Height

```{r}
# Height with ExpDes
with(data, fat2.dic(Subst, Rate, log(Height), quali = c(TRUE, FALSE), fac.names = c("Substrates", "Rates")))
```


## 2.4. Ploting the results

### 2.4.1. Preparing data

```{r}
# Preparing data
data_plot <- data %>% 
  mutate(test = case_when(
    Trat == 4 | Trat == 5 | Trat == 6 ~ "b",
    Trat == 1 | Trat == 2 | Trat == 3 | Trat == 7 | Trat == 8 ~ "a",
    TRUE ~ as.character(Trat)
  )) %>% 
  mutate(Subst_alt = case_when(
    Subst == 1 ~ "SS",
    Subst == 2 ~ "CS")) %>% 
  mutate(Subst_alt = factor(Subst_alt, levels = c("SS", "CS")))


```


### 2.4.2. Substrates inside rates

```{r}
# Substrates inside rates
ggplot(data_plot, aes(x = Subst_alt, y = Height, color = test)) +
  geom_jitter(alpha = 0.6, height = 0.1, width = 0.1) +
  stat_summary(fun = mean, geom = "point", size = 3, shape = 15, alpha = 0.4) +
  stat_summary(fun = mean, geom = "text", aes(label = sprintf("%.f", after_stat((y)))), position = position_nudge(x = 0.38), family = "sans", size = 4) +
  xlab("Substrates") + ylab("Height (cm)") + 
  scale_color_manual(values = c("#0047AB", "#E3735E")) +
  theme_classic() + tema + 
  facet_grid(~Rate, labeller = labeller(Rate = function(x) paste("CRF:", x, "kg/cm³"))) +
  tema

```


### 2.4.3. Rates inside substrates

```{r}
ggplot(data_plot, aes(x = Rate, y = log(Height), group = Subst_alt, color = Subst_alt, fill = Subst_alt)) +
  geom_smooth(method = "lm", formula = y ~ poly(x, 2), se = TRUE, level = 0.95) +
  stat_summary(fun = mean, geom = "point", size = 3, shape = 15, alpha = 0.6) +
  scale_x_continuous(limits = c(0, 12), breaks = seq(0, 12, 2)) +
  labs(y = "log(Height [cm])", x = expression(Rate ~ (kg ~ m^-3))) +
  annotate("text", x = 7, y = 2.4, parse = TRUE, color = "#FF9999", size = 3, label = "log(Height) == 3.6094 + 0.0547*x - 0.0047*x^2*',' ~~ R^2 == 0.96", family = "serif") +
  annotate("text", x = 7, y = 2.1, parse = TRUE, color = "#0099FF", size = 3, label = "log(Height) == 1.4945 + 0.6638*x - 0.0397*x^2*',' ~~ R^2 == 0.96", family = "serif") +
  scale_color_manual(values = c("#FF9999", "#0099FF"), name = "Substrates:", labels = c("Sewage sludge", "Commercial substrate")) +
  scale_fill_manual(values = c("#FF9999", "#0099FF")) +
  guides(fill = "none", color = guide_legend(override.aes = list(fill = NA))) +
  theme_classic() +
  tema +
  theme(legend.position = "bottom")
```



